---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Install apps with homebrew
      homebrew: name={{ item }} state=present
      with_items:
        - wget
        - vim
        - tmux
        - htop
        - ag
        - git
        - python3
        - zsh
        - bash
        - hugo
        - graphviz
        - tree
        - jenkins
        - neovim
        - openssl
        - nmap
        - shellcheck
        - telnet
        - sqlit
        - wget
        - gh
    - name: Install cask packages
      homebrew_cask: name={{ item }} state=present
      with_items:
        - dropbox
        - visual-studio-code
