---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Install apps with homebrew
      homebrew: name={{ item }} state=present
      with_items:
        - wget
        - vim
        - tmux
        - htop
        - ag
        - git
        - python3
        - zsh
        - bash
        - hugo
        - graphviz
        - tree
        - jenkins
        - neovim
        - openssl
        - nmap
        - shellcheck
        - telnet
        - sqlite
        - wget
        - gh
        - nvm
        - pyenv
        - jq
        - yarn
    - name: Tap a Homebrew repository, state present
      homebrew_tap:
        name: "{{ item }}"
        state: present
      with_items:
        - homebrew/cask-fonts
    - name: Install cask packages
      homebrew_cask: name={{ item }} state=present
      with_items:
        - dropbox
        - visual-studio-code
        - keepassxc
        - zoom
        - font-hack-nerd-font
        - slack
    - name: Install Terraform
      shell: |
        brew tap hashicorp/tap
        brew install hashicorp/tap/terraform
